---
# tasks file for vim
- name: Install neovim
  include_role:
    name: generic_program_install

- name: Install neovim pip package (required by python-mode plugin)
  pip:
    name: neovim
    executable: /usr/bin/pip3

- name: Make Nvim required symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - {'src': ~/.vim, 'dest': ~/.config/nvim}
    - {'src': ~/.vimrc, 'dest': ~/.config/nvim/init.vim}

- name: Install Vundle
  git:
    repo: https://git.fok.systems/lyz/super_bash_prompt
    dest: ~/.vim/bundle

- name: Test if the plugins are already installed
  stat:
    path: ~/.vim/bundle/vim-fugitive
  register: vim_fugitive_path
  changed_when: false

- name: Install the plugins
  shell: vim +PluginInstall +qall
  when: not vim_fugitive_path.stat.islnk
