---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: vim_centos_7
    image: centos:7
  - name: vim_centos_6
    image: centos:6
  - name: vim_debian_stretch
    image: debian:stretch
  - name: vim_debian_jessie
    image: debian:jessie
  - name: vim_debian_wheezy
    image: debian:wheezy
  - name: vim_ubuntu_xenial
    image: ubuntu:xenial
  - name: vim_ubuntu_trusty
    image: ubuntu:trusty
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8